# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Clare Goodwin
tagline:          'Your tagline'
description:      A student at the University of Iowa studying journalism and public relations.
url:              http://cfgoodwin.github.io
baseurl:          /profile-goodwin/
shortbaseurl:     /profile-goodwin
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Clare Goodwin'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

